Task #1457217: Create FileFormatFactory for all file formats
AzureAD/rms-sdk-for-cpp pull request #134
Opened 2017-08-22 13:43 UTC by meijin007

2017-08-22 13:43 UTC, msftclas commented
@meijin007,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-22 14:41 UTC, shenhavba commented on sdk/file_sdk/Common/file_format_factory.cpp
> +    return std::find(array.begin(), array.end(), value) != array.end();
>   [](start = 2, length = 2)

2 spaces.
and i don't really care...

2017-08-22 14:45 UTC, shenhavba commented on sdk/file_sdk/Common/file_format_factory.cpp
> +    throw rmscore::exceptions::RMSInvalidArgumentException("The extention is empty");
why do you throw RMSInvalidArgumentException? its not related to rms. i think there is built in exception for invalid argument

2017-08-22 14:48 UTC, shenhavba commented on sdk/file_sdk/Common/file_format_factory.cpp
> +  {
> { [](start = 1, length = 2)

should be in the same line of the if in all places

2017-08-23 05:49 UTC, vakuras requested changes

2017-08-23 05:49 UTC, vakuras commented on sdk/file_sdk/Common/Common.pro
> +INCLUDEPATH += $$REPO_ROOT/sdk/rmscrypto_sdk/CryptoAPI $$REPO_ROOT/sdk/rms_sdk/ModernAPI $$REPO_ROOT/sdk/file_sdk
why do you need the file_sdk? you are in the same project. or not?

2017-08-23 05:49 UTC, vakuras commented on sdk/file_sdk/Common/file_format.h
> +  virtual const vector<Tag> ReadTags() = 0;
why did you remove the &?

2017-08-23 05:49 UTC, vakuras commented on sdk/file_sdk/Common/file_format_factory.cpp
> +bool in_array(const string &value, const vector<string> &array) {
this should be a private method of FileFormatFactory

2017-08-23 05:49 UTC, vakuras commented on sdk/file_sdk/XMPFileFormat/xmp_file_format.cpp
> +  return vector<Tag>();
should throw a not implemented exception for now

2017-08-23 05:49 UTC, vakuras commented on sdk/file_sdk/PFileFileFormat/pfile_file_format.cpp
> +  vector<Tag> tmp;
should throw a not implemented exception for now

2017-08-23 05:49 UTC, vakuras commented on sdk/file_sdk/PDFFileFormat/pdf_file_format.cpp
> +  return vector<Tag>();
should throw a not implemented exception for now

2017-08-23 09:57 UTC, meijin007 commented on sdk/file_sdk/Common/Common.pro
> +INCLUDEPATH += $$REPO_ROOT/sdk/rmscrypto_sdk/CryptoAPI $$REPO_ROOT/sdk/rms_sdk/ModernAPI $$REPO_ROOT/sdk/file_sdk
we should not use .. in #include

---
In reply to: [134661416](https://github.com/AzureAD/rms-sdk-for-cpp/pull/134#discussion_r134661416) [](ancestors = 134661416)

2017-08-23 10:35 UTC, shenhavba approved these changes
:shipit:

2017-08-23 18:06 UTC, vakuras approved these changes

2017-08-23 18:06 UTC, vakuras commented on sdk/file_sdk/Common/file_format_factory.cpp
> +std::shared_ptr<IFileFormat> FileFormatFactory::Create(std::shared_ptr<IStream> fileStream, const string& extension) {
just stream

2017-08-27 05:46 UTC, merged