Task #1459163: Write tests for FileFormatFactory
AzureAD/rms-sdk-for-cpp pull request #137
Opened 2017-08-30 13:42 UTC by meijin007

2017-08-30 13:42 UTC, msftclas commented
@meijin007,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-30 14:07 UTC, vakuras commented on sdk/file_sdk/UnitTests/common_ut/common_ut.cpp
> +void CommonTests::Create_StreamIsNull_ThrowInvlidArgument()
typo

2017-08-30 14:09 UTC, vakuras commented on sdk/file_sdk/UnitTests/common_ut/common_ut.cpp
> +void CommonTests::Create_ExtenstionWithoutDot_AddsDot()
what about the case of passing .xxx.pfile?

2017-08-30 14:10 UTC, vakuras commented on sdk/file_sdk/UnitTests/common_ut/common_ut.cpp
> +  QFETCH(std::string, extenstion);
typo

2017-08-30 14:10 UTC, vakuras requested changes
:clock1:

2017-08-31 07:33 UTC, vakuras commented on sdk/file_sdk/Common/file_format_factory.cpp
> +    pos = finalExtention.find_last_of('.');
this line exist only for the point of not getting into the next if

2017-08-31 08:00 UTC, vakuras approved these changes
:shipit:

2017-08-31 08:05 UTC, shenhavba commented on sdk/file_sdk/UnitTests/common_ut/istream_mock.cpp
> +IStreamMock::IStreamMock()
the "{" in this file are not in the same line

2017-08-31 08:06 UTC, shenhavba approved these changes
:shipit:

2017-08-31 08:23 UTC, merged